### ISSUE TITLE
Latest GEVI, searching titles with digits in them corrected

### ISSUE THREAD

**Issue by JPH71** [acvigue/pgma#9]
Cody had determined that titles such as
(Treasure Island Media) - Cheap Thrills 11 (2019).mp4 were not being found in GEVI as the search could not process the '11' in the title.

Agent has being corrected so that the search query looks for "
Cheap Thrills" only and searches through the results until it finds the correct title

[GEVI.bundle.zip](https://github.com/acvigue/pgma/files/4079603/GEVI.bundle.zip)

**Comment by CodyBerenson** [comment]
terrific, thanks!

**Comment by CodyBerenson** [comment]
That worked!

**Comment by JPH71** [comment]
Brilliant xx

**Comment by acvigue** [comment]
pull request, please... No offense intended, but if you have the time to develop all of these new scrapers, then please take the 30 minutes to learn how to setup a local copy of the repository and develop & push your changes. I am not on here that much anymore because 90% of what I do is just download, edit, branch, push, and merge these files. It could be made 10x as efficient and I could spend the time I am available here developing plugins. Thanks.

**Comment by acvigue** [comment]
Thank you very much for the contribution! Sorry if that last comment came off as rude, it was not intended.

**Comment by CodyBerenson** [comment]
Aiden:  it is clear that you are frustrated.  I've now read the GitHub online tutorial, installed the desktop app. However, other than posting a file in an issues window, we do not have writes to create a branch or upload/push changes in which to initiate pull requests.  We're going to need your help, partnership, and collaboration please.

**Comment by CodyBerenson** [comment]
Pull request worked.  Issue  can be closed.

**Comment by JPH71** [comment]
woo hooo
